import net.neoforged.gradle.dsl.common.runs.run.Run

base {
    archivesName = mod_id
}
dependencies {
    jarJar(project( ":more_rarity"))
    //jarJar(project( ":extend_iss"))
    jarJar(project( ":uncompleted_way_spellbook"))
    jarJar(project( ":almost_one_attribute"))
    jarJar(project( ":core"))

}
// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

